# Generated by Django 5.2.1 on 2025-06-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tamaño', models.CharField(choices=[('S', 'Pequeño'), ('M', 'Mediano'), ('L', ' Grande'), ('XL', 'Extra Grande')], max_length=2)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado')], max_length=15)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('estado_salud', models.CharField(choices=[('buena', 'Buena'), ('moderada', 'Moderada'), ('requiere_atencion', 'Requiere atención ')], max_length=20)),
                ('vacunado', models.BooleanField()),
                ('temperamento', models.CharField(choices=[('amigable', 'Amigable'), ('agresivo', 'Agresivo'), ('nervioso', 'Nervioso'), ('jugueton', 'Juguetón'), ('tranquilo', 'Tranquilo')], max_length=20)),
            ],
        ),
    ]
