# Generated by Django 5.2.1 on 2025-06-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('telf', models.CharField(max_length=15)),
                ('preferencias', models.CharField(choices=[('caniche', 'Caniche'), ('pitbull', 'Pitbull'), ('labrador', 'Labrador'), ('doverman', 'Doverman'), ('callejero', 'Callejero'), ('otro', 'Otro')], max_length=50)),
                ('historial_adopciones', models.ManyToManyField(blank=True, to='adopciones.perro')),
            ],
        ),
    ]
