# Generated by Django 5.2.1 on 2025-06-15 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_usuarioadoptante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioadoptante',
            options={'verbose_name': 'Usuario adoptante', 'verbose_name_plural': 'Usuarios adoptantes'},
        ),
    ]
